name: lamp-php-switch
services:

  apache:
    image: apache
    container_name: apache
    hostname: apache
    env_file:
      - ./.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      internal_net:
        ipv4_address: 172.16.1.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Shared by Apache and FPM
      - type: bind
        source: ./vhosts
        target: /srv/apache2/vhosts/
        read_only: false
      - type: volume
        source: fpm-sockets-dir
        target: /run/php/
        read_only: false
      # SSL Certs
      - type: bind
        source: ./apache/ssl/certs
        target: /etc/ssl/export
        read_only: false
      # Config files editable on the host and monitored by watchmedo
      - type: bind
        source: ./vhosts-configs
        target: /etc/apache2/fpm-sites
        read_only: false

  php:
    image: php-fpm:${PHP_VERSION}
    container_name: php-fpm-${PHP_VERSION}
    hostname: php-${PHP_VERSION}
    tty: true
    stdin_open: true
    env_file:
      - ./.env
    networks:
      internal_net:
        ipv4_address: 172.16.1.11
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      # Shell login ubuntu
      - type: bind
        source: ./shell/ubuntu/.bashrc.d/
        target: /home/ubuntu/.bashrc.d/
        read_only: false
      - type: bind
        source: ./shell/ubuntu/files
        target: /home/ubuntu/.host-data
        read_only: false
      - type: bind
        source: ./shell/ubuntu/.mysql
        target: /home/ubuntu/.mysql
        read_only: false
      - type: bind
        source: ./shell/ubuntu/.ssh
        target: /home/ubuntu/.ssh
        read_only: false
      # Shared by Apache and FPM
      - type: bind
        source: ./vhosts
        target: /srv/apache2/vhosts/
        read_only: false
      - type: volume
        source: fpm-sockets-dir
        target: /run/php/
        read_only: false
      # MariaDB via socket
      - type: volume
        source: mariadb-sockets-dir
        target: /run/mysqld/

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:lts
    command: ["--ssl=0"]
    ports:
      - "3306:3306"
    networks:
      internal_net:
        ipv4_address: 172.16.1.12
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql/
      - type: volume
        source: mariadb-sockets-dir
        target: /run/mysqld/

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  mysql-data:
  mariadb-sockets-dir:
  fpm-sockets-dir:
  vhosts:
