SSLEngine on
SSLCertificateFile      /opt/pki/certs/wildcard.lamp.localhost.crt
SSLCertificateKeyFile   /opt/pki/private/wildcard.lamp.localhost.key
SSLProtocol -all +TLSv1.2 +TLSv1.3
# SSLCipherSuite HIGH:!aNULL:!MD5
# SSLHonorCipherOrder on
# Header always set Strict-Transport-Security "max-age=31536000"
