[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
user=root

[program:apache2]
command=/usr/sbin/apache2 -DFOREGROUND
autostart=true
autorestart=true
startretries=999
exitcodes=0
stopsignal=TERM
stopasgroup=true
killasgroup=true

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:config_monitor]
directory=/etc/apache2
command=watchmedo shell-command --patterns="*" --recursive --command='
    echo "Config changed, testing..."
    if apachectl configtest; then
        echo "OK → graceful reload"
        apachectl graceful
    else
        echo "BROKEN config → skip reload"
    fi
  ' fpm-sites
user=root
autostart=true
autorestart=true

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
