name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PHP_VERSION: 8.3

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create temporary .env file
      run: |
        cp .env-example .env
        echo "HOST_UID=$(id -u)" >> .env
        echo "HOST_GID=$(id -g)" >> .env

    - name: Build and start compose stack
      run: |
        make build-cert
        make build-apache
        make build-single-php PHP_VERSION=8.3
        make up
        docker compose ps -a

    - name: Allow containers to initialize
      run: sleep 5

    - name: Check running containers
      run: |
        RUNNING=$(docker compose ps -q --filter "status=running" | wc -l)
        TOTAL=$(docker compose config --services | wc -l)
        (( 1 + RUNNING == TOTAL )) || (docker compose ps && exit 1)

    - name: Configure local DNS routing
      run: echo "127.0.0.1 examplehost.lamp.localhost" | sudo tee -a /etc/hosts

    - name: Install custom SSL Root CA
      run: |
        sudo cp ./apache/ssl/certs/lamp.localhost-rootCA.crt /usr/local/share/ca-certificates/lamp.localhost-rootCA.crt
        sudo update-ca-certificates

    - name: Test HTTP Response
      run: |
        set +e
        curl -sS -f -D - http://localhost:80/ | egrep "Apache2 Ubuntu Default Page" > /dev/null
        PIPE_RTS=("${PIPESTATUS[@]}")

        CURL_EXIT=${PIPE_RTS[0]}
        GREP_EXIT=${PIPE_RTS[1]}

        if [ $CURL_EXIT -ne 0 ]; then
          echo "[FAIL] Connection failed. (curl exit code: $CURL_EXIT)"
          exit 1
        fi
        
        if [ $GREP_EXIT -ne 0 ]; then
          echo "[FAIL] Expected content not found. (grep exit code: $GREP_EXIT)"
          exit 1
        fi

    - name: Test HTTPS Response
      run: |
        set +e
        curl -sS -f -D - https://examplehost.lamp.localhost:443/ | egrep "www.php.net" > /dev/null
        PIPE_RTS=("${PIPESTATUS[@]}")

        CURL_EXIT=${PIPE_RTS[0]}
        GREP_EXIT=${PIPE_RTS[1]}

        if [ $CURL_EXIT -ne 0 ]; then
          echo "[FAIL] Connection failed. (curl exit code: $CURL_EXIT)"
          exit 1
        fi
        
        if [ $GREP_EXIT -ne 0 ]; then
          echo "[FAIL] Expected content not found. (grep exit code: $GREP_EXIT)"
          exit 1
        fi

    - name: Shutdown LAMP Stack
      if: always()
      run: make down
